networks:
  app-network:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - API_HOST=api
      - DB_HOST=database
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    depends_on:
      - database
      - api
    networks:
      - app-network

  database:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - app-network
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q \"SELECT 1\""]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: app-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped

  # grafana: 
  #   image: grafana/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
  #   restart: always
  #   ports:
  #     - 1337:3000
  #   networks:
  #     - app-network

volumes:
  mssqldata:

