networks:
  app-network:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - API_HOST=api
      - DB_HOST=database
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    depends_on:
      - database
      - api
    networks:
      - app-network

  database:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - app-network
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q \"SELECT 1\""]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: app-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 9999:80
      - 5341:5341
    volumes:
      - seq-logs:/data
    networks:
      - app-network

  seqcli:
    image: datalust/seqcli:latest
    command: apikey create -t newapikey --token 12345678901234567890 -s http://seq
    depends_on:
      - seq
    restart: on-failure
    networks:
      - app-network
volumes:
  mssqldata:

