networks:
  demoblazorapp:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
      - Kestrel__EndPoints__Http__Url=http://+:8080
    ports:
      - 4001:8080
    networks:
      - demoblazorapp

  demoappdb:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: