networks:
  app-network:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - API_HOST=api
      - DB_HOST=database
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
    depends_on:
      - database
      - api
    networks:
      - app-network

  database:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - app-network
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q \"SELECT 1\""]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: app-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped

  dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: app-dashboard
    # environment:
    #   - DASHBOARD__OTLP__AUTHMODE=ApiKey
    #   - DASHBOARD__OTLP__PRIMARYAPIKEY=12345678901234567890
    ports:
    - 18888:18888
    networks:
    - app-network

volumes:
  mssqldata:

