networks:
  app-network:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - API_HOST=api:8080
      - DB_HOST=db
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
      - Kestrel__EndPoints__Http__Url=http://+:8080
    ports:
      - 9001:8080
    networks:
      - app-network

  db:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - app-network
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    image: app-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - Kestrel__EndPoints__Http__Url=http://+:8080
    networks:
      - app-network

volumes:
  mssqldata:

