networks:
  app-network:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - API_HOST=api
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    ports:
      - 80
    networks:
      - app-network

  demoappdb:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - app-network
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    image: app-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    # ports:
    #   - 5001:80
    networks:
      - app-network

volumes:
  mssqldata:

